### ISSUE TITLE
Add to Chrome Extension web store?

### ISSUE THREAD

**Issue by danawoodman** [NorfeldtAbtion/github-issue-reactions-browser-extension#10]
@NorfeldtAbtion what do you think about adding to the chrome web store? I could help with this if you want?

PS, thanks for adding me as a collaborator!

PPS I do see the note in the readme but I figured would could entertain adding it to help users adopt it more readily?

**Comment by Norfeldt** [comment]
I have placed it under a MIT license so you are welcome to do whatever pleases you with it.

I personally don't wanna put it myself on the chrome extension due to various reasons like:

- time (got other projects that also needs attention)
- Security: https://developer.chrome.com/docs/extensions/mv2/security/

I know that is not an optimal way for distribution since it requires a pull and reload inside the extension settings, but it won't happen too often and cloning it and pressing the watch isn't too bad.

**Comment by Norfeldt** [comment]
@danawoodman it is now in store 🎁: 
https://chrome.google.com/webstore/detail/github-issue-reactions/enekincdenmmbpgkbhflknhaphpajnfd
